import './globals.css'
import { Dosis } from 'next/font/google'
import Favicon from './favicon.ico'
import Footer from '@/components/Footer/footer'
import Navbar from '@/components/Navbar/navbar'
import Header from '@/components/Header/header'

const dosis = Dosis({ subsets: ['latin']})

export const metadata = {
   title: 'Piras Massage',
   description: 'Generated by create next app',
   icon: { Favicon },
 }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={dosis.className}>
        <Header />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
