"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer/footer'
import Navbar from '@/components/Navbar/navbar'
import Header from '@/components/Header/header'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Piras Massage',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header /><Navbar />{children}<Footer />
      </body>
    </html>
  )
}
